// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZjU3OWESgnEe_RdQYpYO-LiS429kZt4g',
    appId: '1:419427863862:web:ccc1d93fca0f3dd1d4b797',
    messagingSenderId: '419427863862',
    projectId: 'flutterwladitodo',
    authDomain: 'flutterwladitodo.firebaseapp.com',
    storageBucket: 'flutterwladitodo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8VMvp12QajGFjGcG4lF76tPnw3GCCeZI',
    appId: '1:419427863862:android:9f14726d3336bdd6d4b797',
    messagingSenderId: '419427863862',
    projectId: 'flutterwladitodo',
    storageBucket: 'flutterwladitodo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtV_qaEHlz1FaTmkYNxspsTuvrHql7VmE',
    appId: '1:419427863862:ios:ddbe53897bbc1191d4b797',
    messagingSenderId: '419427863862',
    projectId: 'flutterwladitodo',
    storageBucket: 'flutterwladitodo.appspot.com',
    androidClientId: '419427863862-04c07kmmc17svf922dpbff8maq1243iv.apps.googleusercontent.com',
    iosClientId: '419427863862-sljue8e0nk0bhbnva64t1edc5iul5pth.apps.googleusercontent.com',
    iosBundleId: 'com.bandeira.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtV_qaEHlz1FaTmkYNxspsTuvrHql7VmE',
    appId: '1:419427863862:ios:ddbe53897bbc1191d4b797',
    messagingSenderId: '419427863862',
    projectId: 'flutterwladitodo',
    storageBucket: 'flutterwladitodo.appspot.com',
    androidClientId: '419427863862-04c07kmmc17svf922dpbff8maq1243iv.apps.googleusercontent.com',
    iosClientId: '419427863862-sljue8e0nk0bhbnva64t1edc5iul5pth.apps.googleusercontent.com',
    iosBundleId: 'com.bandeira.todo',
  );
}
